@startuml
set separator none
title Pawfect Care - Diagnostic Service - Components

top to bottom direction
skinparam ranksep 60
skinparam nodesep 30

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<PawfectCare.DiagnosticService.CreateDiagnosticCommandFromResourceAssembler>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam database<<PawfectCare.DiagnosticDB>> {
  BackgroundColor #f5da55
  FontColor #000000
  BorderColor #ab983b
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService.DiagnosticCommandService>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService.DiagnosticCommandServiceImpl>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService.DiagnosticController>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService.DiagnosticQueryService>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService.DiagnosticQueryServiceImpl>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService.DiagnosticRepository>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService.DiagnosticResourceFromEntityAssembler>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.MedicalRecordService>> {
  BackgroundColor #22b140
  FontColor #ffffff
  BorderColor #177b2c
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.RegistryService>> {
  BackgroundColor #22b140
  FontColor #ffffff
  BorderColor #177b2c
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService.UpdateDiagnosticCommandFromResourceAssembler>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
  shadowing false
}
skinparam rectangle<<PawfectCare.DiagnosticService>> {
  BorderColor #177b2c
  FontColor #177b2c
  shadowing false
}

rectangle "==Registry Service\n<size:10>[Container: Netflix Eureka, Spring Cloud]</size>\n\nService registry for microservice discovery" <<PawfectCare.RegistryService>> as PawfectCare.RegistryService
rectangle "==Medical Record Service\n<size:10>[Container: Spring Boot]</size>\n\nStores and provides access to pet medical histories" <<PawfectCare.MedicalRecordService>> as PawfectCare.MedicalRecordService
database "==Diagnostic DB\n<size:10>[Container: PostgreSQL]</size>\n\nPostgreSQL database for diagnostic service" <<PawfectCare.DiagnosticDB>> as PawfectCare.DiagnosticDB

rectangle "Diagnostic Service\n<size:10>[Container: Spring Boot]</size>" <<PawfectCare.DiagnosticService>> {
  rectangle "==DiagnosticController\n<size:10>[Component: Spring Boot]</size>\n\nREST controller for diagnostics" <<PawfectCare.DiagnosticService.DiagnosticController>> as PawfectCare.DiagnosticService.DiagnosticController
  rectangle "==DiagnosticCommandServiceImpl\n<size:10>[Component: Spring Boot]</size>\n\nImplements DiagnosticCommandService" <<PawfectCare.DiagnosticService.DiagnosticCommandServiceImpl>> as PawfectCare.DiagnosticService.DiagnosticCommandServiceImpl
  rectangle "==DiagnosticQueryServiceImpl\n<size:10>[Component: Spring Boot]</size>\n\nImplements DiagnosticQueryService" <<PawfectCare.DiagnosticService.DiagnosticQueryServiceImpl>> as PawfectCare.DiagnosticService.DiagnosticQueryServiceImpl
  rectangle "==DiagnosticCommandService\n<size:10>[Component: Spring Boot]</size>\n\nDefines command operations" <<PawfectCare.DiagnosticService.DiagnosticCommandService>> as PawfectCare.DiagnosticService.DiagnosticCommandService
  rectangle "==DiagnosticQueryService\n<size:10>[Component: Spring Boot]</size>\n\nDefines query operations" <<PawfectCare.DiagnosticService.DiagnosticQueryService>> as PawfectCare.DiagnosticService.DiagnosticQueryService
  rectangle "==DiagnosticRepository\n<size:10>[Component: Spring Boot]</size>\n\nPersists and retrieves Diagnostic entities" <<PawfectCare.DiagnosticService.DiagnosticRepository>> as PawfectCare.DiagnosticService.DiagnosticRepository
  rectangle "==DiagnosticResourceFromEntityAssembler\n<size:10>[Component: Spring Boot]</size>\n\nConverts Entity → DTO" <<PawfectCare.DiagnosticService.DiagnosticResourceFromEntityAssembler>> as PawfectCare.DiagnosticService.DiagnosticResourceFromEntityAssembler
  rectangle "==CreateDiagnosticCommandFromResourceAssembler\n<size:10>[Component: Spring]</size>\n\nConverts DTO → CreateDiagnosticComma" <<PawfectCare.DiagnosticService.CreateDiagnosticCommandFromResourceAssembler>> as PawfectCare.DiagnosticService.CreateDiagnosticCommandFromResourceAssembler
  rectangle "==UpdateDiagnosticCommandFromResourceAssembler\n<size:10>[Component: Spring]</size>\n\nConverts DTO → UpdateDiagnosticComma" <<PawfectCare.DiagnosticService.UpdateDiagnosticCommandFromResourceAssembler>> as PawfectCare.DiagnosticService.UpdateDiagnosticCommandFromResourceAssembler
}

PawfectCare.RegistryService .[#707070,thickness=2].> PawfectCare.MedicalRecordService : "<color:#707070>Uses"
PawfectCare.DiagnosticService.DiagnosticController .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticCommandServiceImpl : "<color:#707070>invokes"
PawfectCare.DiagnosticService.DiagnosticController .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticQueryServiceImpl : "<color:#707070>invokes"
PawfectCare.DiagnosticService.DiagnosticCommandServiceImpl .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticCommandService : "<color:#707070>implements"
PawfectCare.DiagnosticService.DiagnosticQueryServiceImpl .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticQueryService : "<color:#707070>implements"
PawfectCare.DiagnosticService.DiagnosticController .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticResourceFromEntityAssembler : "<color:#707070>uses"
PawfectCare.DiagnosticService.DiagnosticController .[#707070,thickness=2].> PawfectCare.DiagnosticService.CreateDiagnosticCommandFromResourceAssembler : "<color:#707070>uses"
PawfectCare.DiagnosticService.DiagnosticController .[#707070,thickness=2].> PawfectCare.DiagnosticService.UpdateDiagnosticCommandFromResourceAssembler : "<color:#707070>uses"
PawfectCare.DiagnosticService.DiagnosticCommandServiceImpl .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticRepository : "<color:#707070>persists data to"
PawfectCare.DiagnosticService.DiagnosticQueryServiceImpl .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticRepository : "<color:#707070>queries data from"
PawfectCare.RegistryService .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticController : "<color:#707070>discovers"
PawfectCare.DiagnosticService.DiagnosticRepository .[#707070,thickness=2].> PawfectCare.DiagnosticDB : "<color:#707070>reads from and writes to"
PawfectCare.MedicalRecordService .[#707070,thickness=2].> PawfectCare.DiagnosticService.DiagnosticController : "<color:#707070>requests diagnostic information"
@enduml