@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam person<<1>> {
  BackgroundColor #39b56e
  FontColor #ffffff
  BorderColor #277e4d
}
person "==Person, Usuario" <<1>>

skinparam person<<2>> {
  BackgroundColor #7bb9e4
  FontColor #ffffff
  BorderColor #56819f
}
person "==Person, veterinario" <<2>>

skinparam rectangle<<3>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
}
rectangle "==Software System" <<3>>

skinparam rectangle<<4>> {
  BackgroundColor #7b7b7b
  FontColor #ffffff
  BorderColor #565656
  roundCorner 20
}
rectangle "==Software System, External System" <<4>>

rectangle "." <<_transparent>> as 5
5 .[#707070,thickness=2].> 5 : "<color:#707070>Relationship"


@enduml